# Generated by Django 4.0.1 on 2022-02-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_categoryview_categoryview2_category_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryView2',
        ),
    ]
